ENV['PATH'] = ENV['PATH'] + ';C:\Bitnami\redmine-3.0.0-0/git/bin'
ENV['PATH'] = ENV['PATH'] + ';/bin'
ENV['PATH'] = ENV['PATH'] + ';C:\Bitnami\redmine-3.0.0-0\imagemagick'
ENV['MAGICK_CODER_MODULE_PATH'] = 'C:\Bitnami\REDMIN~1.0-0\IMAGEM~1\modules\coders'
ENV['PATH'] = ENV['PATH'] + ';C:\Bitnami\redmine-3.0.0-0\ruby\bin'
